### ISSUE TITLE
Perftop MacOS crashes without error

### ISSUE THREAD

**Issue by Jon-AtAWS** [opendistro-for-elasticsearch/perftop#10]
The following dashboard file causes perftop-mac-os to crash. The issue is that it lacks a dimension. We need to have some kind of useful error message rather than just quit silently.

{
  "endpoint": "localhost:9600",
  "gridOptions": {
    "rows": 12,
    "cols": 12
  },
  "graphs": {
    "lines": [
      {
        "queryParams" : {
          "metrics": "Segments_Memory",
          "aggregates": "sum"
        },
        "options": {
          "gridPosition": {
            "row": 0,
            "col": 0,
            "rowSpan": 12,
            "colSpan": 6
          },
          "label": "Memory usage",
          "showNthLabel": 3,
          "showLegend": true,
          "legend": { "width": 10 },
          "xAxis": ["0:00", "0:05", "0:10", "0:15", "0:20", "0:25", "0:30", "0:35", "0:40", "0:45", "0:50", "0:55"],
          "refreshInterval": 5000
        }
      }
    ]
  }
}

**Comment by yeajung** [comment]
Hi,

Please refer to "Error Handling" section of the Design Doc (https://github.com/opendistro-for-elasticsearch/perftop/blob/master/docs/DesignDoc.md). We do silent fails on most errors so that one widget configuration doesn't crash the entire dashboard.

For debugging, you can pass in "--logfile ${filepath}" to see if there are any error messages.
